# Generated by Django 5.0.4 on 2024-05-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
