# Generated by Django 5.0.4 on 2024-05-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
