<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-11 10:53

from django.db import migrations
=======
# Generated by Django 5.0.4 on 2024-05-10 12:11

from django.db import migrations, models
>>>>>>> tri-dev


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish List'},
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='customer_imgs/'),
        ),
>>>>>>> tri-dev
    ]
