# Generated by Django 5.0.4 on 2024-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_demo_url_product_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='puslished',
            field=models.BooleanField(default=False),
        ),
    ]
