# Generated by Django 5.0.4 on 2024-05-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_puslished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='puslished',
            new_name='published_status',
        ),
    ]
