# Generated by Django 4.2.13 on 2024-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_vendor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
