# Generated by Django 5.0.4 on 2024-05-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_vendor_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_status',
        ),
    ]
