# Generated by Django 5.0.4 on 2024-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_product_demo_url_remove_product_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_img',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
    ]
