# Generated by Django 5.0.4 on 2024-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_vendor_description_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.TextField(null=True),
        ),
    ]
