# Generated by Django 5.0.4 on 2024-05-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_total_amount_alter_orderitems_price_and_more'),
        ('main', '0023_vendor_description_alter_order_total_amount_and_more'),
    ]

    operations = [
    ]
