# Generated by Django 5.0.4 on 2024-05-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_merge_20240522_1324'),
        ('main', '0024_order_order_address'),
    ]

    operations = [
    ]
